name: Run E2E Tests Action
on:
  pull_request:

jobs:
  run-e2e-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]

    services:
      api-solid-pg:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          - POSTGRESQL_USERNAME=docker
          - POSTGRESQL_PASSWORD=docker
          - POSTGRESQL_DATABASE=apisolid

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Run E2E Tests
      run: pnpm test:e2e
      env:
        JWT_SECRET: testing
        DATABASE_URL: "postgresql://docker:docker@localhost:5432/apisolid?schema=public"